piipod/dashboard/views.py
from flask import Blueprint, request, redirect, g
from piipod.views import current_user, login_required, url_for, current_user
from piipod.group.forms import GroupForm
from piipod.models import Group
from piipod.defaults import default_group_roles


dashboard = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@dashboard.url_value_preprocessor
def load_current_user(_, __):
    pass


def render_dashboard(f, *args, **kwargs):
    """custom render for dashboard"""
    from piipod.views import render
    return render(f, *args, **kwargs)


#############
# DASHBOARD #
#############


@dashboard.route('/')
@login_required
def home():
    """user dashboard"""
    return render_dashboard('dashboard/index.html', groups=current_user().groups())


@dashboard.route('/g/', methods=['GET', 'POST'])
@login_required
def create_group():
    """create group form"""
    form = GroupForm(request.form)
    if request.method == 'POST' and form.validate():
        group = Group.from_request().save().load_roles(
            default_group_roles[request.form['category']]).save()
        current_user().join(group, role='Owner')
        group.load_settings('whitelist')
        return redirect(url_for('group.home', group_url=group.url))
    return render_dashboard('public/form.html',
        title='Create Group',
        submit='create',
        form=form)

piipod/templates/base.html
<html>
  <head>
    <title>{{ title }}</title>
    <!-- scale mobile version correctly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- third-party code -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:300,400,700|Raleway:300' rel='stylesheet' type='text/css'>
    <script   src="http://code.jquery.com/jquery-2.2.2.min.js"   integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="   crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
    <!-- custom code -->
    <link rel="stylesheet" href="{{ domain }}{{ the_url('static', filename='style.css') }}">
    <script>
$(document).ready(function() {
  $('.select').on('click', function() {
    $(this).toggleClass('s');
  })
});
    </script>
    {% block head %}
    {% endblock %}
  </head>
  {% block body %}
  {% endblock %}
</html>

piipod/templates/confirm.html
{% extends "group/base.html" %}
{% block main %}
<main class="sp-main">
  <section class="sp-module-list module">
    <p class="sf-back"><a href="{{ back or the_url('public.home') }}"><span class="sf-back-arr">&larr;</span> back</a></p>
    <h2>{{ title }}</h2>
    <p class="sp-byline">{{ message | safe }}</p>
    {% if url %}
    <a href="{{ url }}" class="button">{{ action }}</a>
    {% endif %}
  </section>
</main>
{% endblock %}

piipod/templates/error.html
{% extends "group/base.html" %}
{% block main %}
<main class="sp-main">
  <section class="sp-module-list module">
    <p class="sf-back"><a href="{{ back or the_url('public.home') }}"><span class="sf-back-arr">&larr;</span> back</a></p>
    <h1 class="sp-title">{{ code }}</h1>
    <p class="sp-byline">{{ message | safe }}</p>
    {% if url and action %}
    <a href="{{ url }}" class="button">{{ action }}</a>
    {% endif %}
  </section>
</main>
{% endblock %}

piipod/templates/footer.html
<footer class="authorship col-md-12 col-xs-12">
  <p class="col-md-12 author">created by <a href="http://alvinwan.com">Alvin Wan</a> &middot; project on <a href="http://github.com/alvinwan/piiipod">Github</a></p>
</footer>

piipod/templates/index.html
{% extends "public/base.html" %}
{% block main %}
<main class="sp-main">
  <section class="sp-module-banner module">
    <h2>Welcome!</h2>
    <p>Here are all of the people using Piipod today. {% if not current_user.is_authenticated %}Click "Sign in" in the top right to get started.{% else %}<a href="{{ url_for('dashboard.create_group') }}">Create a group</a> to get started! {% endif %}</p>
    <table>
      <tbody>
        <tr><th>Name</th><th class="hidden-xs">Description</th><th>Category</th></tr>
        {% for group in groups %}
        <tr><td><a href="{{ url_for('group.home', group_url=group.url) }}">{{ group.name }}</a></td><td class="hidden-xs">{{ group.description[:20]}}</td><td>{{ group.category }}</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</main>
{% endblock %}